version: '3.6'
services:
  worker:
    build: ../../.
    image: onetwotrip:latest
    restart: always
    depends_on:
      - redis
    environment:
      NODE_ENV: development
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:6379"
networks:
  default:
    external:
      name: onetwotrip_net